version: '3.7'

services:
  agent:
    image: "rancher/k3s:v1.25.14-k3s1"
    tmpfs:
      - /run
      - /var/run
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    privileged: true
    restart: always
    environment:
      - K3S_URL=https://199.168.117.36:6443
      - K3S_TOKEN=aPuGh+5UDskRAbkLaXRzFoSOcSM+5vAK+NEYOWHJH7w=