version: '3.7'

services:
  consul-server:
    image: hashicorp/consul:1.16
    container_name: consul-server
    network_mode: "host"
    restart: always
    volumes:
      - ./server.json:/consul/config/server.json:ro
    command: "agent -bootstrap-expect=2"