version: '3.7'

services:
  consul-server:
    image: hashicorp/consul:1.16
    container_name: consul-server
    network_mode: "host"
    restart: always
    environment:
      CONSUL_HTTP_TOKEN: "e95b599e-166e-7d80-08ad-aee76e7ddf19"
    volumes:
      - ./server.json:/consul/config/server.json:ro
    command: "agent -bootstrap-expect=2"