version: '3.7'

services:
  consul-server:
    image: consul:latest
    container_name: consul-server
    restart: always
    volumes:
      - ./server.json:/consul/config/server.json:ro
    networks:
      - consul
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    command: "agent"