version: '3.7'

services:
  consul-client:
    image: hashicorp/consul:1.16
    container_name: consul-client
    restart: always
    ports:
      - "8500:8500"
    volumes:
      - ./client.json:/consul/config/client.json:ro
    command: "agent"